services:
  web-react-app:
    build:
      context: .
      dockerfile: ${DOCKER_FILE}
    ports:
      - "3000:${PORT}"
    volumes:
      - /app/node_modules # don't overwrite the containers app module on changes
      - .:/app # map changes from root of local machine to the /app folder
  tests:
    stdin_open: true # attach to stdin
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
